<a href="https://colab.research.google.com/github/Jakbarov7/LearnDataScienceBootcamp/blob/main/pandas/Np_arr01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

1. Birinchi usul : array funksiyasi yordamida . Ushbu funksiya har qanday turdagi ketma-ket ma'lumotlarni qabul qilib, uni yangi Numpy arrayiga o'girib beradi.

In [ ]:
data = [2, 4, 6, 8, 10]
arr = np.array(data)
arr

array([ 2,  4,  6,  8, 10])

In [ ]:
type(arr)

numpy.ndarray

In [ ]:
data2 = (1, 3, 5, 7, 9)
arr2 = np.array(data2)
arr2

array([1, 3, 5, 7, 9])

ndim yordamida arr o'lchamini aniqlash

In [ ]:
print("arr ning o'lchami:", arr.ndim, "ga teng.")
print("arr2 ning o'lchami:", arr2.ndim, "ga teng.")

arr ning o'lchami: 1 ga teng.
arr2 ning o'lchami: 1 ga teng.


2D arr . Nested list yordamida

In [ ]:
# Nested listdan foydalaniladi
data2d = [[1, 3, 5, 7], [2, 4, 6, 8]]
arr2d = np.array(data2d)
arr2d

array([[1, 3, 5, 7],
       [2, 4, 6, 8]])

In [ ]:
# o'lchamini aniqlimiz
arr2d.ndim

2

shape va size metodlari :
  1. shape - qator va ustunlar sonini aniqliydi
  2. size - massiv elementlar sonini aniqliydi

In [ ]:
print(arr)

[ 2  4  6  8 10]


In [ ]:
arr.shape # qator va ustunlar sonini aniqlimiz

(5,)

In [ ]:
arr.size # nechta elementi borligini aniqlimiz

5

In [ ]:
print(arr2)

[1 3 5 7 9]


In [ ]:
arr2.shape

(5,)

In [ ]:
arr2.size

5

In [ ]:
print(arr2d)

[[1 3 5 7]
 [2 4 6 8]]


In [ ]:
# qator va ustunlari
arr2d.shape

(2, 4)

In [ ]:
# elementlari soni
arr2d.size

8

3D massiv yaratish | boshlanishidagi va tugashidagi to'rtburchak qavslar 3 tadan bo'lishi kerak !

In [ ]:
data3d = [[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]], [[13, 14, 15], [16, 17, 18]]]
arr3d = np.array(data3d)
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [ ]:
# o'chamini aniqlimiz
arr3d.ndim

3

In [ ]:
# qator va ustunlarini aniqlimiz
arr3d.shape # javobi: (3 ta 2d arr, 2qatordan, 3ustundan iborat)

(3, 2, 3)

In [ ]:
# elementlar sonini aniqlimiz
arr3d.size

18

Zeros va Ones yordamida NumPy massiv yaratish :
  1. zeros - barcha qiymatlari 0 dan iborat qator va ustunlari sonini aniq berishimiz bilan massiv yasab beradi
  2. ones - barcha qiymatlari 1 dan tashkil topgan buyam sheypini berishimiz kerak bo'ladi

In [ ]:
# zeros
arrZero = np.zeros(shape=(3, 4))
arrZero

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
# shape= qilib yozmasegam bo'ladi
arrZ2 = np.zeros((2, 3))
arrZ2

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
# Ones
arrOne = np.ones(shape=(3, 4))
arrOne

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
arrO2 = np.ones((2, 3))
arrO2

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
# arrZero ni barcha ma'lumotlarini ko'ramiz
print(arrZero.ndim) # o'lchami
print(arrZero.shape) # qator va ustunlari
print(arrZero.size) # elementlari soni

2
(3, 4)
12


In [ ]:
# arrOne ni barcha ma'lumotlarini ko'ramiz
print(arrOne.ndim) # o'lchami
print(arrOne.shape) # qator va ustunlari
print(arrOne.size) # elementlari soni

2
(3, 4)
12


arange funksiyasi bilan massiv yaratish :
  1. default holati : arange(5) # 0~5 gacha sonlarni beradi
  2. start, stop : arange(5, 10) # 5~10 gacha sonlarni beradi
  3. start, stop, step : arange(1, 20, 2) # 1~20 gacha 2 qadam bilan oberadi

In [ ]:
# default holati
arrArn = np.arange(5)
arrArn

array([0, 1, 2, 3, 4])

In [ ]:
# start, stop bilan
arr_arn2 = np.arange(5, 15)
arr_arn2

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
# start, stop, step bilan
arr_arn3 = np.arange(2, 28, 2) # 2 dan 28 gacha 2 qadam bilan juft sonlarni oberadi
arr_arn3

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26])

Random funksiyasi orqali massiv yaratish :

  1. rand - 0 va 1 oralig'idagi taxminiy sonlarni beradi
    ishlatilishi 3 xil : 1)rand() - 1 ta float_son beradi , 2)rand(5) - 5 ta float_son beradi(1D arr), 3) rand(3, 4)- 3ga 4 o'lchamdagi 2D arr beradi , 5)rand(2, 3, 4)-2ta 2D li arr va 3 ga 4 bo'lgan 3D arr beradi .

  2. randint - belgilangan chegaradan tasodifiy 1ta butun sonni beradi buniyam yuqoridagi kabi 1ta butun_son , 1D, 2D va 3D arrlar va ularni tayplari bilan osa bo'ladi

  3. randn - buyam yuqoridagi kabi bitta son, 1D, 2D va 3D arrlarni osa bo'ladi faqat 0 va 1 oraligida ba'zida manfiy ko'pincha musbat sonlarni beradi

**rand - ga misollar ko'ramiz**

In [ ]:
# 0 va 1 oraligidan bitta musbat son
arrR1 = np.random.rand()
arrR1

0.5171052289994332

In [ ]:
# 0 va 1 oraligidan 3 ta son
arrR2 = np.random.rand(3)
arrR2

array([0.26798653, 0.26368096, 0.39194248])

In [ ]:
# 3ga 4 o'lchamli 2D arr
arrR3 = np.random.rand(3, 4)
arrR3

array([[0.23112982, 0.63184033, 0.62810943, 0.23900887],
       [0.31229249, 0.3935921 , 0.24194571, 0.17813597],
       [0.10165389, 0.57254969, 0.77857281, 0.6269321 ]])

In [ ]:
# 3D arr
arrR4 = np.random.rand(2, 3, 2)
arrR4

array([[[0.67664015, 0.1708414 ],
        [0.3611017 , 0.46697322],
        [0.65411169, 0.29733239]],

       [[0.88648155, 0.96020805],
        [0.26925069, 0.13247495],
        [0.30148504, 0.50505077]]])

**randint - misollar ko'ramiz** | randint(3, 10) # 3~10 ga sonlardan bitta oberadi

randint(2, 15, size=3) # 2~15 gacha 3 ta butun son beradi

randint(0, 10, size=(3, 4)) # 0~10 gacha 3ga 4 2D arr beradi

In [ ]:
# 3 va 10 oraligidan bitta son beradi
aR1 = np.random.randint(3, 10)
aR1

9

In [ ]:
# 2 va 15 oraligidan 4 ta son beradi
aR2 = np.random.randint(2, 15, size=4)
aR2

array([13,  5,  5,  6])

In [ ]:
# 4 va 23 oraligidagi 3ga 4 2D arr beradi
aR3 = np.random.randint(4, 23, size=(3, 4))
print(aR3)
print(aR3.ndim)

[[13 14 10 12]
 [10  6 12 19]
 [21 10  4 21]]
2


In [ ]:
aR4 = np.random.randint(20, 35, size=(2, 3, 4))
print(aR4)
print(aR4.ndim)

[[[21 34 21 22]
  [31 21 29 29]
  [28 34 34 33]]

 [[24 27 26 26]
  [23 26 24 31]
  [21 21 27 26]]]
3


**randn - misollar ko'ramiz**

In [ ]:
# 0 va 1 oraligida bazida manfiy kopincha musbat bitta son beradi
arr_r1 = np.random.randn()
arr_r1

0.9479937734376171

In [ ]:
# bazilari manfiy kopinchasi musbat 5 ta son beradi
arr_r2 = np.random.randn(5)
arr_r2

array([ 0.45975647,  0.5913596 , -0.00974134, -1.39479455,  1.23792139])

In [ ]:
# 3ga 4 arr beradi
arr_r3 = np.random.randn(3, 4)
arr_r3

array([[ 1.20836072,  1.802469  , -0.31757097, -0.25154104],
       [ 1.10496336, -0.4030476 , -1.43542228,  0.86910187],
       [-0.2861899 ,  1.00415131,  0.82996974,  1.2433423 ]])

In [ ]:
# 3D arr beradi
arr_r4 = np.random.randn(2, 3, 4)
arr_r4

array([[[ 0.23261041, -1.5950748 ,  0.78468918, -0.7614719 ],
        [-1.75464847, -0.04698063,  0.32058865, -0.39721265],
        [ 0.6001358 , -1.13430397, -0.34866815,  1.07681349]],

       [[-0.17285167, -0.11906091, -0.47673615, -0.28478568],
        [-1.13112533,  1.17845774, -1.32087636,  2.42721292],
        [-1.64418613, -1.08263899,  0.03898269,  0.67747016]]])