<a href="https://colab.research.google.com/github/Jakbarov7/LearnDataScienceBootcamp/blob/main/numpy/boolean_index_04.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
arr1 = np.arange(10, 101, 10)
arr1

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [4]:
# qiymatlarni boolean ma'lumot turiga o'girish
arr1_bool = (arr1 > 60)
arr1_bool

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [6]:
# 60 dan katta sonlarni boolean yordamida olish
arr1[arr1_bool]

array([ 70,  80,  90, 100])

In [13]:
arr2 = np.arange(100, 125, 3)
arr2

array([100, 103, 106, 109, 112, 115, 118, 121, 124])

In [14]:
arr2_bool = (arr2 == 106)
arr2_bool

array([False, False,  True, False, False, False, False, False, False])

In [15]:
arr2[arr2_bool]

array([106])