<a href="https://colab.research.google.com/github/Jakbarov7/LearnDataScienceBootcamp/blob/main/numpy/boolean_index_04.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
arr1 = np.arange(10, 101, 10)
arr1

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [3]:
# 50 dan yuqori sonlarni boolean indekslash bilan olish
arr1_bool = arr1 > 50
arr1_bool

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [4]:
arr1[arr1_bool]

array([ 60,  70,  80,  90, 100])

In [5]:
names = np.array(['Hasan', 'Husan', 'Ali', 'Vali', 'Hasan', 'Elyor', 'Husan', 'Vali', 'Samandar'])
names

array(['Hasan', 'Husan', 'Ali', 'Vali', 'Hasan', 'Elyor', 'Husan', 'Vali',
       'Samandar'], dtype='<U8')

In [6]:
names_bool = (names == 'Hasan')
names_bool

array([ True, False, False, False,  True, False, False, False, False])

In [7]:
names[names_bool]

array(['Hasan', 'Hasan'], dtype='<U8')

In [8]:
arr2 = np.arange(1, 11)
arr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
# qoldiqli sonlarni boolean indekslash bilan olish
arr2_bool = (arr2 % 2 != 0)
arr2_bool

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [10]:
arr2[arr2_bool]

array([1, 3, 5, 7, 9])

In [11]:
# juft sonlarni boolean indekslash yordamida olish
arr2_even = (arr2 % 2 == 0)
arr2_even

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [12]:
arr2[arr2_even]

array([ 2,  4,  6,  8, 10])

In [13]:
names = np.array(['Hasan', 'Husan', 'Mirasil', 'Elyor', 'Hasan', 'Abdurashid', 'Elyor', 'Samandar', 'Javlon'])
data = np.random.randn(9, 4)
print(names)
print(data)

['Hasan' 'Husan' 'Mirasil' 'Elyor' 'Hasan' 'Abdurashid' 'Elyor' 'Samandar'
 'Javlon']
[[ 0.20457603  0.55837733 -0.08757705  0.21832374]
 [ 1.05963767  0.52931394  0.8513215  -0.72357758]
 [ 0.33738559 -0.11556443 -1.95124554 -0.38387169]
 [-2.06410615  0.14161197 -1.21070827 -0.09186457]
 [ 1.88743775 -1.37466192  0.89383742 -0.08434933]
 [ 1.4483409  -0.89190835  0.65105365 -0.30590373]
 [-0.27282516 -0.52878736  0.9021734   0.21018736]
 [-1.39977038 -0.227824   -0.38542281  0.20040654]
 [ 2.0337312  -0.04880847 -2.07393834  0.47765687]]


In [14]:
names == 'Elyor'

array([False, False, False,  True, False, False,  True, False, False])

In [15]:
# Elyorga tegishli ma'lumotlarni olish
data[names == 'Elyor']

array([[-2.06410615,  0.14161197, -1.21070827, -0.09186457],
       [-0.27282516, -0.52878736,  0.9021734 ,  0.21018736]])

In [16]:
# Elyorga tegishli ma'lumotlarni ohirgi ikki qatorini olish
data[names == 'Elyor', -1]

array([-0.09186457,  0.21018736])

In [17]:
# 1-ustun ma'lumotlarini olish
data[names == 'Elyor', 1]

array([ 0.14161197, -0.52878736])

In [20]:
# Elyordan boshqa barcha insonlarni ma'lumotlarini olish
data[names != 'Elyor']

array([[ 0.20457603,  0.55837733, -0.08757705,  0.21832374],
       [ 1.05963767,  0.52931394,  0.8513215 , -0.72357758],
       [ 0.33738559, -0.11556443, -1.95124554, -0.38387169],
       [ 1.88743775, -1.37466192,  0.89383742, -0.08434933],
       [ 1.4483409 , -0.89190835,  0.65105365, -0.30590373],
       [-1.39977038, -0.227824  , -0.38542281,  0.20040654],
       [ 2.0337312 , -0.04880847, -2.07393834,  0.47765687]])

In [22]:
# yuqoridagi bilan bir xil natija beradi
data[~(names == 'Elyor')]

array([[ 0.20457603,  0.55837733, -0.08757705,  0.21832374],
       [ 1.05963767,  0.52931394,  0.8513215 , -0.72357758],
       [ 0.33738559, -0.11556443, -1.95124554, -0.38387169],
       [ 1.88743775, -1.37466192,  0.89383742, -0.08434933],
       [ 1.4483409 , -0.89190835,  0.65105365, -0.30590373],
       [-1.39977038, -0.227824  , -0.38542281,  0.20040654],
       [ 2.0337312 , -0.04880847, -2.07393834,  0.47765687]])

In [24]:
# bir vaqtning o'zida ikki va undan ortiq insonlarni ma'lumotlarini olish
mask = (names == 'Elyor') | (names == 'Hasan')
mask

array([ True, False, False,  True,  True, False,  True, False, False])

In [27]:
data[mask]

array([[ 0.20457603,  0.55837733, -0.08757705,  0.21832374],
       [-2.06410615,  0.14161197, -1.21070827, -0.09186457],
       [ 1.88743775, -1.37466192,  0.89383742, -0.08434933],
       [-0.27282516, -0.52878736,  0.9021734 ,  0.21018736]])

In [28]:
data[mask, -1]

array([ 0.21832374, -0.09186457, -0.08434933,  0.21018736])