<a href="https://colab.research.google.com/github/Jakbarov7/LearnDataScienceBootcamp/blob/main/numpy/dtype_02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
# massiv yaratishda uning ma'lumot turini kiritish
arr1 = np.array([0.1, 2.3, 3.4, 4.5], dtype=np.float16)
arr1

array([0.1, 2.3, 3.4, 4.5], dtype=float16)

In [3]:
type(arr1)

numpy.ndarray

In [4]:
# massivning ma'lumot turini aniqlash
arr1.dtype

dtype('float16')

In [5]:
arr2 = np.array([-1, 2, -3.2, 4, -5])
arr2.dtype

dtype('float64')

In [6]:
# bir turdagi ma'lumot turidan boshqa ma'lumot turiga o'tish
arr3 = np.arange(10, 101, 10)
arr3.dtype

dtype('int64')

In [7]:
arr3_copy = arr3.astype(np.float16)
arr3_copy

array([ 10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.],
      dtype=float16)

In [8]:
arr3_copy.dtype

dtype('float16')

In [9]:
arr4 = np.array([1.1, -2.2, 3.3, -4.4, 5.5], dtype=np.float16)
arr4

array([ 1.1, -2.2,  3.3, -4.4,  5.5], dtype=float16)

In [10]:
arr4_copy = arr4.astype(np.int8)
arr4_copy

array([ 1, -2,  3, -4,  5], dtype=int8)

In [12]:
arr4_copy.dtype

dtype('int8')