<a href="https://colab.research.google.com/github/Jakbarov7/LearnDataScienceBootcamp/blob/main/numpy/files_11.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
arr = np.arange(10, 101, 10)
arr

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [3]:
arr1 = np.random.randn(4, 3)
arr1

array([[-1.45252893,  1.75813677, -1.0468754 ],
       [-0.04386572, -0.88145334,  0.76457706],
       [-0.55111632,  0.93122347,  0.74008913],
       [ 0.3019084 ,  0.68194463,  0.39340965]])

In [4]:
arr2 = np.array(['Hasan', 'Husan', 'Olim', 'Alijon', 'Valijon', 'Teshavoy'])
arr2

array(['Hasan', 'Husan', 'Olim', 'Alijon', 'Valijon', 'Teshavoy'],
      dtype='<U8')

In [5]:
# massivni faylga yozish
np.save('Birinchi massiv', arr)

In [6]:
# faylga yozilgan massivni o'qish
birinchi_m = np.load('Birinchi massiv.npy')

In [7]:
birinchi_m

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [8]:
# bir vaqtda ikki va undan ortiq massivlarni faylga yozish
np.savez('massivlar', a=arr1, b=arr2)

In [11]:
# bir qancha massivlar saqlangan faylni o'qish
massivlar = np.load('massivlar.npz')
massivlar

NpzFile 'massivlar.npz' with keys: a, b

In [12]:
# arr1 ni olish
massivlar['a']

array([[-1.45252893,  1.75813677, -1.0468754 ],
       [-0.04386572, -0.88145334,  0.76457706],
       [-0.55111632,  0.93122347,  0.74008913],
       [ 0.3019084 ,  0.68194463,  0.39340965]])

In [13]:
# arr2 ni olish
massivlar['b']

array(['Hasan', 'Husan', 'Olim', 'Alijon', 'Valijon', 'Teshavoy'],
      dtype='<U8')