<a href="https://colab.research.google.com/github/Jakbarov7/LearnDataScienceBootcamp/blob/main/numpy/index_slicing_03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [4]:
arr1 = np.arange(10, 101, 10)
arr1

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [5]:
# 20
arr1[1]

20

In [6]:
# 50
arr1[4]

50

In [7]:
# 90
arr1[-2]

90

In [8]:
arr1

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [9]:
# 40, 50
arr1[3:5]

array([40, 50])

In [10]:
# 70, 80, 90
arr1[-4:-1]

array([70, 80, 90])

In [11]:
arr_slic = arr1[2:4]
arr_slic

array([30, 40])

In [12]:
arr_slic[0] = -22
arr_slic[1] = -44
arr_slic

array([-22, -44])

In [13]:
arr1

array([ 10,  20, -22, -44,  50,  60,  70,  80,  90, 100])

In [14]:
# Yuqoridagini aksi , asosiy massivni elementlarini o'zgartirmagan holda , uning elementlari ustida amallar bajarish
arr2_slic = arr1[2:4].copy()
arr2_slic

array([-22, -44])

In [16]:
arr2_slic[0] = 0
arr2_slic[1] = 1000
arr2_slic

array([   0, 1000])

In [17]:
arr1

array([ 10,  20, -22, -44,  50,  60,  70,  80,  90, 100])