<a href="https://colab.research.google.com/github/Jakbarov7/LearnDataScienceBootcamp/blob/main/numpy/index_slicing_03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [18]:
import numpy as np

In [19]:
arr1 = np.arange(10, 101, 10)
arr1

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [20]:
# 20
arr1[1]

20

In [21]:
# 50
arr1[4]

50

In [22]:
# 90
arr1[-2]

90

In [23]:
arr1

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [24]:
# 40, 50
arr1[3:5]

array([40, 50])

In [25]:
# 70, 80, 90
arr1[-4:-1]

array([70, 80, 90])

In [26]:
arr_slic = arr1[2:4]
arr_slic

array([30, 40])

In [27]:
arr_slic[0] = -22
arr_slic[1] = -44
arr_slic

array([-22, -44])

In [28]:
arr1

array([ 10,  20, -22, -44,  50,  60,  70,  80,  90, 100])

In [29]:
# Yuqoridagini aksi , asosiy massivni elementlarini o'zgartirmagan holda , uning elementlari ustida amallar bajarish
arr2_slic = arr1[2:4].copy()
arr2_slic

array([-22, -44])

In [30]:
arr2_slic[0] = 0
arr2_slic[1] = 1000
arr2_slic

array([   0, 1000])

In [31]:
arr1

array([ 10,  20, -22, -44,  50,  60,  70,  80,  90, 100])

**2D va 3D larda indekslash va kesib olish**

In [32]:
# 2D massivda kesib olish
lst2d = [[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]
arr2d = np.array(lst2d)
arr2d

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [33]:
# 8
arr2d[2, 1]

8

In [34]:
# 6
arr2d[1, -1]

6

In [36]:
# 10
arr2d[-1, 0]

10

In [37]:
# 4, 5
arr2d[1, 0:2]

array([4, 5])

In [38]:
arr2d

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [39]:
# 11, 12
arr2d[-1, 1:]

array([11, 12])

In [40]:
# 1, 2, 3
arr2d[0]

array([1, 2, 3])

In [41]:
# 3D massivda kesib olish
lst3d = [[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]], [[13, 14, 15], [16, 17, 18]]]
arr3d = np.array(lst3d)
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [42]:
# 6
arr3d[0][1, -1]

6

In [43]:
# 11
arr3d[1][1, 1]

11

In [44]:
# 16
arr3d[-1][-1, 0]

16

In [45]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [46]:
# 2, 3
arr3d[0][0, 1:]

array([2, 3])

In [47]:
# 7, 8
arr3d[1][0, 0:2]

array([7, 8])

In [48]:
# 17, 18
arr3d[-1][-1, 1:]

array([17, 18])