<a href="https://colab.research.google.com/github/Jakbarov7/LearnDataScienceBootcamp/blob/main/numpy/np_arr_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
# array funksiyasi bilan massiv yaratish
lst = [2, 4, 6, 8, 10]
arr1 = np.array(lst)
arr1

array([ 2,  4,  6,  8, 10])

In [3]:
print(type(lst))
print(type(arr1))

<class 'list'>
<class 'numpy.ndarray'>


In [4]:
lst2 = [-1.1, 2, -3.2, 0, 4, 5.4]
arr2 = np.array(lst2)
arr2

array([-1.1,  2. , -3.2,  0. ,  4. ,  5.4])

In [5]:
tpl = (1.1, 2, -3.1, 4.2, -5.3, 6)
arr3 = np.array(tpl)
arr3

array([ 1.1,  2. , -3.1,  4.2, -5.3,  6. ])

In [6]:
print(type(tpl))
print(type(arr3))

<class 'tuple'>
<class 'numpy.ndarray'>


In [7]:
# massivning hajmini aniqlash
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)

1
1
1


In [9]:
# massivning qator va ustunlar sonini aniqlash
print(arr1.shape)
print(arr2.shape)
print(arr3.shape)

(5,)
(6,)
(6,)


In [11]:
# massivning nechta elementi borligini aniqlash
print(arr1.size)
print(arr2.size)
print(arr3.size)

5
6
6


**massiv yaratishni boshqa usullari :**
- arange
- zeros , ones

In [12]:
# arange : start, stop, step
arr4 = np.arange(1, 11) # 1-10
arr4

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
type(arr4)

numpy.ndarray

In [14]:
arr5 = np.arange(10, 101, 10)
arr5

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [15]:
arr6 = np.arange(20)
arr6

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [16]:
arr7 = np.zeros((3, 2))
arr7

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [17]:
arr8 = np.ones((4, 4))
arr8

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:
print(arr8.shape)
print(arr8.size)

(4, 4)
16


**ikki va uch o'lchovli massivlar yaratish**

In [23]:
# 2D massiv yaratish - python_nested_list
arr9 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr9

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
arr9.ndim

2

In [25]:
arr9.shape

(3, 3)

In [26]:
arr9.size

9

In [27]:
lst10 = [[-1, -2, -3], [-4, -5, -6], [-7, -8, -9]]
arr10 = np.array(lst10)
arr10

array([[-1, -2, -3],
       [-4, -5, -6],
       [-7, -8, -9]])

In [28]:
# 3D massiv yaratish
lst_3D = [[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]]
arr_3D = np.array(lst_3D)
arr_3D

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [29]:
print(arr_3D.ndim)
print(arr_3D.shape)
print(arr_3D.size)

3
(2, 2, 3)
12
