<a href="https://colab.research.google.com/github/Jakbarov7/LearnDataScienceBootcamp/blob/main/numpy/sorting_09.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
arr = np.array([10, 5, 8, 12, 3, 7])
arr

array([10,  5,  8, 12,  3,  7])

In [3]:
# tartiblashni birinchi usuli
sort_arr = np.sort(arr)
sort_arr

array([ 3,  5,  7,  8, 10, 12])

In [4]:
arr

array([10,  5,  8, 12,  3,  7])

In [5]:
# tartiblashni ikkinchi usuli
arr.sort()

In [6]:
arr

array([ 3,  5,  7,  8, 10, 12])

In [7]:
arr2 = np.arange(1, 11)
arr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
# massiv elementlarini teskari tartiblash
rev_arr2 = -np.sort(-arr2)
rev_arr2

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [10]:
arr2d = np.array([[12, 5, 7], [3, 8, 10], [6, 15, 2]])
arr2d

array([[12,  5,  7],
       [ 3,  8, 10],
       [ 6, 15,  2]])

In [14]:
arr2d

array([[12,  5,  7],
       [ 3,  8, 10],
       [ 6, 15,  2]])

In [12]:
# 2D arrni ustun bo'yicha tartiblash
np.sort(arr2d, axis=0)

array([[ 3,  5,  2],
       [ 6,  8,  7],
       [12, 15, 10]])

In [13]:
# 2D arrni qator bo'yicha tartiblash
np.sort(arr2d, axis=1)

array([[ 5,  7, 12],
       [ 3,  8, 10],
       [ 2,  6, 15]])