<a href="https://colab.research.google.com/github/Jakbarov7/LearnDataScienceBootcamp/blob/main/numpy/statistics_08.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
# sum
arr2d.sum()

45

In [4]:
# mean
arr2d.mean()

5.0

In [6]:
# ustun bo'yicha yig'indini hisoblash
arr2d.sum(axis=0)

array([12, 15, 18])

In [7]:
# qatorlar bo'yicha yig'indini hisoblash
arr2d.sum(axis=1)

array([ 6, 15, 24])

In [8]:
# ustun bo'yicha o'rtacha qiymatni aniqlash
arr2d.mean(axis=0)

array([4., 5., 6.])

In [9]:
# qator bo'yicha o'rtacha qiymatni aniqlash
arr2d.mean(axis=1)

array([2., 5., 8.])

In [12]:
arr2 = np.array([1, 2, 3, 4, 5])
arr2

array([1, 2, 3, 4, 5])

In [11]:
arr2.cumsum()

array([ 1,  3,  6, 10, 15])

In [14]:
# massivning maksimum elementini aniqlash
arr2.max()

5

In [15]:
arr2.min()

1

In [17]:
arr2

array([1, 2, 3, 4, 5])

In [18]:
# cumsum ni ko'paytirilgan ko'rinishi
arr2.cumprod()

array([  1,   2,   6,  24, 120])

In [19]:
arr2.std()

1.4142135623730951

In [20]:
arr2.var()

2.0