<a href="https://colab.research.google.com/github/Jakbarov7/LearnDataScienceBootcamp/blob/main/numpy/trnaspose_05.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [3]:
arr1 = np.arange(10, 22).reshape(3, 4)
arr1

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [4]:
arr1.shape

(3, 4)

In [5]:
# Transpose qilish
arr1.T

array([[10, 14, 18],
       [11, 15, 19],
       [12, 16, 20],
       [13, 17, 21]])

In [6]:
arr1.swapaxes(1, 0)

array([[10, 14, 18],
       [11, 15, 19],
       [12, 16, 20],
       [13, 17, 21]])