<a href="https://colab.research.google.com/github/Jakbarov7/LearnDataScienceBootcamp/blob/main/numpy/unique_10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
arr = np.array([1, 2, 2, 3, 4, 4, 4, 5, 6, 6, 7])
arr

array([1, 2, 2, 3, 4, 4, 4, 5, 6, 6, 7])

In [3]:
# massiv elementlarini takrorlanmas qilib chiqarish
np.unique(arr)

array([1, 2, 3, 4, 5, 6, 7])

In [5]:
arr1 = np.array([1, 3, 5, 7, 9])
arr2 = np.array([2, 4, 6, 7, 1])

In [6]:
np.in1d(arr1, arr2)

array([ True, False, False,  True, False])

In [7]:
np.setdiff1d(arr1, arr2)

array([3, 5, 9])