<a href="https://colab.research.google.com/github/Jakbarov7/LearnDataScienceBootcamp/blob/main/numpy/universal_functions_06.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [6]:
arr1 = np.arange(10, 46, 2).reshape(3, 6)
arr1

array([[10, 12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30, 32],
       [34, 36, 38, 40, 42, 44]])

In [9]:
# har bir elementni kvadrat ildizini hisoblab beradi
np.sqrt(arr1)

array([[3.16227766, 3.46410162, 3.74165739, 4.        , 4.24264069,
        4.47213595],
       [4.69041576, 4.89897949, 5.09901951, 5.29150262, 5.47722558,
        5.65685425],
       [5.83095189, 6.        , 6.164414  , 6.32455532, 6.4807407 ,
        6.63324958]])

In [11]:
# har bir elementni kvadratga oshiradi
np.square(arr1)

array([[ 100,  144,  196,  256,  324,  400],
       [ 484,  576,  676,  784,  900, 1024],
       [1156, 1296, 1444, 1600, 1764, 1936]])

In [12]:
arr1 = np.arange(1, 11)
arr2 = np.arange(11, 21)
print(arr1)
print(arr2)

[ 1  2  3  4  5  6  7  8  9 10]
[11 12 13 14 15 16 17 18 19 20]


In [13]:
np.add(arr1, arr2)

array([12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [15]:
# mos elementlarni ko'paytiradi
np.multiply(arr1, arr2)

array([ 11,  24,  39,  56,  75,  96, 119, 144, 171, 200])

In [17]:
# ikki massivni mos elementlarini solishtirib , kattasini oberadi
np.maximum(arr1, arr2)

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])