<a href="https://colab.research.google.com/github/Jakbarov7/LearnDataScienceBootcamp/blob/main/numpy/where_07.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

In [4]:
arr1 = np.arange(1, 11)
arr2 = np.arange(11, 21)
print(arr1)
print(arr2)

[ 1  2  3  4  5  6  7  8  9 10]
[11 12 13 14 15 16 17 18 19 20]


In [7]:
# shart True bo'lsa arr1 ni oladi , False bo'lganda arr2 ni oladi
cond = np.array([True, True, False, True, False, False, True, True, False, False])
np.where(cond, arr1, arr2)

array([ 1,  2, 13,  4, 15, 16,  7,  8, 19, 20])

In [8]:
arr3 = np.array([100, 110, 113, 95, 120, 93])
arr3

array([100, 110, 113,  95, 120,  93])

In [9]:
# agarda 100 kichik bo'lsa o'sha sonni o'zini aks holda 0 ni yozish
result = np.where(arr3<100, arr3, 0)

In [10]:
result

array([ 0,  0,  0, 95,  0, 93])

In [12]:
indices = np.where(arr1>5)
indices
# bunda 5 dan katta bo'lgan elementlarni indekslarini chiqaradi

(array([5, 6, 7, 8, 9]),)

In [13]:
arr4 = np.random.randn(4, 4)
arr4

array([[-0.52754157, -1.24333294, -0.01961664, -0.10105819],
       [ 0.16305774,  0.38432623,  0.06795879,  1.20144798],
       [-0.02523476,  1.43454268,  0.86527307,  0.33963458],
       [ 0.1705571 ,  0.30630257,  0.11466688,  2.55892718]])

In [14]:
cond = np.where(arr4<0, 0, 1)
cond

array([[0, 0, 0, 0],
       [1, 1, 1, 1],
       [0, 1, 1, 1],
       [1, 1, 1, 1]])